blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import cache_page
from portfolio import views

urlpatterns = [
    path('adm/', admin.site.urls),
    path('', cache_page(60)(views.homepage), name='home'),
    path('contact', views.contactView, name='contact'),
    path('blog/', include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('success/', views.success, name='success')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from datetime import datetime

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(default=None)
    date = models.DateField(default=datetime.now)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio/forms.py
from django import forms
from captcha.fields import CaptchaField


class ContactForm(forms.Form):
    first_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={'placeholder': 'Как Вас зовут',
                   'class': "form-control",
                   'style': 'max-width: auto;'
                   }
        )
    )
    captcha = CaptchaField()

    email_address = forms.CharField(
        max_length=100,
        widget=forms.EmailInput(
            attrs={'placeholder': 'E-mail',
                   'class': "form-control",
                   'style': 'max-width: auto;'
                   })
    )

    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(
            attrs={'placeholder': 'Ваш текст',
                   'class': "form-control",
                   'style': 'max-width: auto;'
                   })
    )

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blog = Blog.objects.order_by('-date')
    return render(request, 'blog/blog_home.html', {'blog':blog})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.urls import reverse_lazy
from .models import Project
from .forms import ContactForm


def homepage(request):
    project = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': project})


def contactView(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Message about form"
            body = {
                'first_name': form.cleaned_data['first_name'],
                'email': form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())
            try:
                send_mail(subject, message,
                          'alexvl92@yandex.ru',
                          ['alexej.92@yandex.ru'])
            except BadHeaderError:
                return HttpResponse('Найден некорректный заголовок')
            return redirect("success")

    form = ContactForm()
    return render(request, "portfolio/contact.html", {'form': form})


def success(request):
    return render(request, 'portfolio/success.html')

blog/templates/blog/blog_home.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}



<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>


<h3 class="text-center mb-5">Alex has written {{ blog.count }} blog{{ blog.count|pluralize }}</h3>

{% for post in blog %}
    <div class="row justify-content-center my-3">
        <div class="col-md-10">
            <a href="{% url 'blog:detail' post.id %}">
                <h2>{{ post.title }}</h2>
            </a>
        <h5 class="text-muted">{{ post.date|date:'M d Y'|upper }}</h5>
        <h4>{{ post.description|striptags|truncatechars:100 }}</h4>
    </div>
</div>



{% endfor %}
    
{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>
<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static "portfolio/icon_logo.png" %}">

    <title>Alex Vladimirov</title>
</head>

<body>

<nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static "portfolio/python-acc9c68ff62d73618344379ce3e645c9.png" %}" width="60" height="30"
                 class="d-inline-block align-top" alt="Alex's Logo">
            <span>Alex Vladimirov</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% static "portfolio/resume.pdf" %}" target="_blank">Resume</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://vk.com/id11977958" target="_blank">Vk</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://t.me/Alex_Vl92" target="_blank">Telegram</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/Alex-V92" target="_blank">GitHub</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
                </li>
                <li>
                    <a role="button" href="{% url 'contact' %}" class="btn btn-primary">Связаться со мной</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/contact.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

    <div style="margin:80px" class="container3">
        <div class="col-md-9 text-center">
            <h1>Контакты</h1>
            <h4>Напишите мне, если у вас есть вопросы</h4>
        </div>
    </div>


    <form method="POST" class="field">
        {% csrf_token %}
        <div>{{ form.first_name }}</div>
        <div>{{ form.email_address }}</div>
        <div>{{ form.message }}</div>
        <div>{{ form.captcha }}</div>

        <button type="submit" class="btn btn-success">Отправить</button>
    </form>


{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

    <div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/415716948.jpeg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Beginner python developer</h1>
  </div>
</div>


    <h1 class="mt-5">Portfolio</h1>
    <hr>
    <div class="row">
        {% for project in projects %}
        <div class="col-lg-4 col-md-6">
            {% if project.url %}
                <a href="{{ project.url }}">
                  <img src="{{ project.image.url }}" class="img-fluid mb-2">
                </a>
            {% else %}

            <img src="{{ project.image.url }}" class="img-fluid mb-2">
            {% endif %}
            <h3>{{ project.title }}</h3>
            <p>{{ project.description }}</p>
    </div>
  {% endfor %}
</div>
</div>

{% endblock %}

portfolio/templates/portfolio/success.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}


    <div class="row justify-content-center my-3">
        <div class="col-5">
            <img src="{% static 'portfolio/check-img.jpg' %}" class="img-fluid" alt="success">
        </div>
    </div>

    <div class="row justify-content-center mb-3">
        <div class="col-md-9 text-center">
            <h1 id="hometext" class="font-weight-bold">Сообщение успешно отправлено</h1>
            <p>Вы будете автоматически перенаправлены на домашнюю страницу
                через 5 секунд.</p>
            <a href={% url 'home' %}>Если этого не произошло нажмите сюда</a>
            <meta http-equiv="refresh" content="3; {% url 'home' %}">
        </div>
    </div>

{% endblock %}
p